---
- name: Comprehensive Cloudera Manager Service Configuration Update
  hosts: cm_server
  vars_files:
    - ../inventories/production/group_vars/cm_servers.yml
  vars:
    primary_db_password: "{{ vault_primary_db_password }}"
    secondary_db_password: "{{ vault_secondary_db_password }}"

  tasks:
    # 1. Authentication
    - name: Get CM API auth token
      uri:
        url: "https://{{ cm_host }}:7183/api/v40/auth/signin"
        method: POST
        body_format: json
        body:
          username: "{{ cm_admin_user }}"
          password: "{{ cm_admin_password }}"
        validate_certs: no
        status_code: 200
      register: auth_result
      no_log: true
      delegate_to: localhost

    - name: Set auth token
      set_fact:
        cm_api_token: "{{ auth_result.json.token }}"
      no_log: true

    # 2. Service discovery with suffix handling
    - name: Get cluster services
      uri:
        url: "https://{{ cm_host }}:7183/api/v40/clusters/{{ cluster_name }}/services"
        method: GET
        headers:
          Authorization: "Bearer {{ cm_api_token }}"
        validate_certs: no
        status_code: 200
      register: cluster_services
      no_log: true

    # 3. Normalize service names (handle hive-1, ranger_kms-1, etc.)
    - name: Create normalized service mapping
      set_fact:
        normalized_services: >-
          {{
            dict(cluster_services.json.items |
                 map(attribute='name') |
                 map('regex_replace', '[-_]\\d+$', '') |
                 map('lower') |
                 zip(cluster_services.json.items | map(attribute='name')) |
                 groupby(0) |
                 map('json_query', '[{key: [0], values: [1[].1]}]') |
                 sum(start=[]) |
                 items2dict
          }}
      no_log: true

    # 4. Service configuration mapping
    - name: Set service configuration mapping
      set_fact:
        service_config_map: {
          'hive': {'type': 'service_level', 'config_key': 'hive_metastore_database_password', 'password': '{{ primary_db_password }}'},
          'hue': {'type': 'service_level', 'config_key': 'database_password', 'password': '{{ primary_db_password }}'},
          'ranger': {'type': 'service_level', 'config_key': 'db_password', 'password': '{{ secondary_db_password }}'},
          'rangerkms': {'type': 'service_level', 'config_key': 'db_password', 'password': '{{ secondary_db_password }}'},
          'yarn': {'type': 'service_level', 'config_key': 'yarn_resourcemanager_store_password', 'password': '{{ primary_db_password }}'},
          'oozie': {'type': 'role_level', 'config_key': 'oozie_database_password', 'password': '{{ primary_db_password }}', 'role_group': 'oozie-OOZIE_SERVER-BASE'},
          'nifiregistry': {'type': 'role_level', 'config_key': 'nifi.registry.db.password', 'password': '{{ secondary_db_password }}', 'role_group': 'nifiregistry-NIFI_REGISTRY_SERVER-BASE'},
          'sqlstreambuilder': {'type': 'role_level', 'config_key': 'spring.datasource.password', 'password': '{{ primary_db_password }}', 'role_group': 'sqlstreambuilder-SQL_STREAM_BUILDER_SERVER-BASE'}
        }
      no_log: true

    # 5. Update service configurations (skips missing services automatically)
    - name: Update service configurations
      block:
        - name: Update service-level configs (Hive, Hue, Ranger, etc.)
          uri:
            url: "https://{{ cm_host }}:7183/api/v40/clusters/{{ cluster_name }}/services/{{ normalized_services[service_type][0] }}/config"
            method: PUT
            headers:
              Authorization: "Bearer {{ cm_api_token }}"
            body_format: json
            body:
              items: [{
                name: "{{ service_config_map[service_type].config_key }}",
                value: "{{ service_config_map[service_type].password }}",
                sensitive: true
              }]
            validate_certs: no
            status_code: 200
          loop: "{{ ['hive','hue','ranger','rangerkms','yarn'] | select('in', normalized_services.keys()) | list }}"
          loop_control:
            loop_var: service_type
          no_log: true
          register: service_config_updates
          retries: 3
          delay: 10

        - name: Update role-level configs (Oozie, NiFi, etc.)
          uri:
            url: "https://{{ cm_host }}:7183/api/v40/clusters/{{ cluster_name }}/services/{{ normalized_services[service_type][0] }}/roleConfigGroups/{{ service_config_map[service_type].role_group }}/config"
            method: PUT
            headers:
              Authorization: "Bearer {{ cm_api_token }}"
            body_format: json
            body:
              items: [{
                name: "{{ service_config_map[service_type].config_key }}",
                value: "{{ service_config_map[service_type].password }}",
                sensitive: true
              }]
            validate_certs: no
            status_code: 200
          loop: "{{ ['oozie','nifiregistry','sqlstreambuilder'] | select('in', normalized_services.keys()) | list }}"
          loop_control:
            loop_var: service_type
          no_log: true
          register: role_config_updates
          retries: 3
          delay: 10

      rescue:
        - name: Log configuration errors
          debug:
            msg: "Error configuring {{ service_type }} - {{ ansible_failed_result.msg }}"
          when: ansible_failed_result is defined

    # 6. Handle Reports Manager (CM Service)
    - name: Check for Reports Manager
      uri:
        url: "https://{{ cm_host }}:7183/api/v40/cm/service"
        method: GET
        headers:
          Authorization: "Bearer {{ cm_api_token }}"
        validate_certs: no
        status_code: 200
      register: cm_service
      no_log: true

    - name: Update Reports Manager configuration
      uri:
        url: "https://{{ cm_host }}:7183/api/v40/cm/service/roleConfigGroups/reportsmanager-REPORTSMANAGER_SERVER-BASE/config"
        method: PUT
        headers:
          Authorization: "Bearer {{ cm_api_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          items: [{
            name: "headlamp_database_password",
            value: "{{ primary_db_password }}",
            sensitive: true
          }]
        validate_certs: no
        status_code: 200
      when: "'REPORTSMANAGER' in (cm_service.json.roles | map(attribute='type') | list)"
      no_log: true

    # 7. Restart services
    - name: Restart modified services
      block:
        - name: Restart cluster services
          uri:
            url: "https://{{ cm_host }}:7183/api/v40/clusters/{{ cluster_name }}/services/{{ normalized_services[service_type][0] }}/commands/restart"
            method: POST
            headers:
              Authorization: "Bearer {{ cm_api_token }}"
            body_format: json
            body: {}
            validate_certs: no
            status_code: 200
          loop: "{{ normalized_services.keys() | intersect(service_config_map.keys()) | list }}"
          loop_control:
            loop_var: service_type
          no_log: true

        - name: Restart Reports Manager
          uri:
            url: "https://{{ cm_host }}:7183/api/v40/cm/service/commands/restart"
            method: POST
            headers:
              Authorization: "Bearer {{ cm_api_token }}"
            body_format: json
            body:
              serviceNames: ["reportsmanager"]
            validate_certs: no
            status_code: 200
          when: "'REPORTSMANAGER' in (cm_service.json.roles | map(attribute='type') | list)"
          no_log: true

      rescue:
        - name: Log restart failures
          debug:
            msg: "Failed to restart {{ service_type }} - {{ ansible_failed_result.msg }}"
          when: ansible_failed_result is defined
